In [2]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error
from sklearn.ensemble import RandomForestRegressor
from sklearn.tree import DecisionTreeRegressor
import catboost as cb

In [2]:
data = pd.read_csv("data.csv")

In [3]:
target = data["sales"]
target

0             0.000
1             0.000
2             0.000
3             0.000
4             0.000
             ...   
3032512     438.133
3032513     154.553
3032514    2419.729
3032515     121.000
3032516      16.000
Name: sales, Length: 3032517, dtype: float64

In [8]:
data = data[['family', 'city', 'state', 'store_type', 'cluster', 'transactions', 'day', 'day_of_week']]


In [9]:
features_train, features_test, target_train, target_test = train_test_split(
    data, target, test_size=0.3, random_state=42, shuffle=True
)

print("Data successfully split into training and testing sets.")

Data successfully split into training and testing sets.


In [10]:
model_rf = RandomForestRegressor(n_jobs=-1, n_estimators=100, random_state=42)
model_rf.fit(features_train, target_train)

predictions_rf = model_rf.predict(features_test)
rmse_rf = mean_squared_error(target_test, predictions_rf, squared=False)
print(f"Random Forest RMSE: {rmse_rf:.2f}")

Random Forest RMSE: 440.51


In [10]:
from sklearn.preprocessing import MinMaxScaler
from sklearn.preprocessing import StandardScaler

In [14]:
scaler = StandardScaler()
data = pd.DataFrame(scaler.fit_transform(data), columns=data.columns)
model_rf = RandomForestRegressor(n_jobs=-1, n_estimators=100, random_state=42)
model_rf.fit(features_train, target_train)

predictions_rf = model_rf.predict(features_test)
rmse_rf = mean_squared_error(target_test, predictions_rf, squared=False)
print(f"Random Forest RMSE: {rmse_rf:.2f}")

Random Forest RMSE: 440.51


In [17]:
scaler = MinMaxScaler()
data = pd.DataFrame(scaler.fit_transform(data), columns=data.columns)
model_rf = RandomForestRegressor(n_jobs=-1, n_estimators=100, random_state=42)
model_rf.fit(features_train, target_train)

predictions_rf = model_rf.predict(features_test)
rmse_rf = mean_squared_error(target_test, predictions_rf, squared=False)
print(f"Random Forest RMSE: {rmse_rf:.2f}")

Random Forest RMSE: 440.51


In [18]:
from sklearn.tree import DecisionTreeRegressor



In [20]:
model = DecisionTreeRegressor(random_state=42)
model.fit(features_train, target_train)

predictions_dt = model.predict(features_test)
rmse_dt = mean_squared_error(target_test, predictions_dt, squared=False)
print(f"Decision Tree RMSE: {rmse_dt:.2f}")


Decision Tree RMSE: 576.38


In [22]:
data = pd.read_csv("data.csv")
target = data["sales"]



In [24]:
data = data[['family', 'city', 'state', 'store_type',
      'cluster', 'transactions','day_of_week']]

In [25]:
features_train, features_test, target_train, target_test = train_test_split(
    data, target, test_size=0.3, random_state=42, shuffle=True
)

print("Data successfully split into training and testing sets.")

Data successfully split into training and testing sets.


In [26]:
model_rf = RandomForestRegressor(n_jobs=-1, n_estimators=100, random_state=42)
model_rf.fit(features_train, target_train)

predictions_rf = model_rf.predict(features_test)
rmse_rf = mean_squared_error(target_test, predictions_rf, squared=False)
print(f"Random Forest RMSE: {rmse_rf:.2f}")

Random Forest RMSE: 470.28


In [6]:
data = pd.read_csv("data.csv")
target = data["sales"]
data = data.drop(columns = ["sales","date"])
data


family  onpromotion  city  state  store_type  cluster  transactions  \
0             0            0     0      0           4       13           0.0   
1             1            0     0      0           4       13           0.0   
2             2            0     0      0           4       13           0.0   
3             3            0     0      0           4       13           0.0   
4             4            0     0      0           4       13           0.0   
...         ...          ...   ...    ...         ...      ...           ...   
3032512      28            0     0      0           2        6        2155.0   
3032513      29            1     0      0           2        6        2155.0   
3032514      30          148     0      0           2        6        2155.0   
3032515      31            8     0      0           2        6        2155.0   
3032516      32            0     0      0           2        6        2155.0   

         event_type  locale  transferred  dcoilwtico  year  month  day  \
0                 3       3        False       93.14  2013      1    1   
1                 3       3        False       93.14  2013      1    1   
2                 3       3        False       93.14  2013      1    1   
3                 3       3        False       93.14  2013      1    1   
4                 3       3        False       93.14  2013      1    1   
...             ...     ...          ...         ...   ...    ...  ...   
3032512           3       1        False       47.57  2017      8   15   
3032513           3       1        False       47.57  2017      8   15   
3032514           3       1        False       47.57  2017      8   15   
3032515           3       1        False       47.57  2017      8   15   
3032516           3       1        False       47.57  2017      8   15   

         day_of_week  salary  
0                  1   False  
1                  1   False  
2                  1   False  
3                  1   False  
4                  1   False  
...              ...     ...  
3032512            1    True  
3032513            1    True  
3032514            1    True  
3032515            1    True  
3032516            1    True  

[3032517 rows x 16 columns]

In [7]:
features_train, features_test, target_train, target_test = train_test_split(
    data, target, test_size=0.3, random_state=42, shuffle=True
)

print("Data successfully split into training and testing sets.")

Data successfully split into training and testing sets.


In [8]:
model_rf = RandomForestRegressor(n_jobs=-1, n_estimators=100, random_state=42)
model_rf.fit(features_train, target_train)

predictions_rf = model_rf.predict(features_test)
rmse_rf = mean_squared_error(target_test, predictions_rf, squared=False)
print(f"Random Forest RMSE: {rmse_rf:.2f}")

Random Forest RMSE: 233.45


In [11]:
scaler = StandardScaler()
data = pd.DataFrame(scaler.fit_transform(data), columns=data.columns)
model_rf = RandomForestRegressor(n_jobs=-1, n_estimators=100, random_state=42)
model_rf.fit(features_train, target_train)

predictions_rf = model_rf.predict(features_test)
rmse_rf = mean_squared_error(target_test, predictions_rf, squared=False)
print(f"Random Forest RMSE: {rmse_rf:.2f}")

Random Forest RMSE: 233.45


In [3]:
data = pd.read_csv("data.csv")

In [4]:
target = data["sales"]
data = data[['family', 'city', 'state', 'store_type', 'cluster', 'transactions', 'day', 'day_of_week']]

In [10]:
from sklearn.model_selection import cross_val_score
model_rf = RandomForestRegressor(n_jobs=-1, n_estimators=100, random_state=42)


In [11]:

model_rf = RandomForestRegressor(n_jobs=-1, n_estimators=100, random_state=42)
print(cross_val_score(model_rf, data, target, cv=5))

[0.4010817         nan 0.83792211 0.8213203  0.85531959]


C:\Users\User\anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py:378: FitFailedWarning: 
1 fits failed out of a total of 5.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
1 fits failed with the following error:
joblib.externals.loky.process_executor._RemoteTraceback: 
"""
Traceback (most recent call last):
  File "C:\Users\User\anaconda3\Lib\site-packages\joblib\externals\loky\process_executor.py", line 343, in _sendback_result
    result_queue.put(_ResultItem(work_id, result=result,
  File "C:\Users\User\anaconda3\Lib\site-packages\joblib\externals\loky\backend\queues.py", line 189, in put
    self._writer.send_bytes(obj)
  File "C:\Users\User\anaconda3\Lib\multiprocessing\connection.py", line 200, in send_bytes
    sel

In [12]:
import numpy as np
from sklearn.metrics import make_scorer
from sklearn.model_selection import cross_val_score

def rmsle(y_true, y_pred):
    return np.sqrt(np.mean((np.log1p(y_true) - np.log1p(y_pred)) ** 2))


rmsle_scorer = make_scorer(rmsle, greater_is_better=False)


scores = cross_val_score(model_rf, data, target, cv=4, scoring=rmsle_scorer)
print(scores)


[-1.7004417  -1.27621092 -0.77792419 -0.75828963]


In [13]:
rmsle_scorer = make_scorer(rmsle, greater_is_better=True)
scores = cross_val_score(model_rf, data, target, cv=5, scoring=rmsle_scorer)
print(scores)


[1.73507923 1.26579099 1.11001864 0.71840047 0.67369835]


In [15]:
data = pd.read_csv("data.csv")
target = data["sales"]
data = data.drop(columns = ["sales","date"])
rmsle_scorer = make_scorer(rmsle, greater_is_better=True)
scores = cross_val_score(model_rf, data, target, cv=5, scoring=rmsle_scorer)
print(scores)
                   

[1.32526016 1.08024645 1.18283261 0.94728469 0.59331761]


In [20]:
l = [1.73507923, 1.26579099, 1.11001864, 0.71840047, 0.67369835]
m = np.mean(l)
print(m)

1.100597536
